### ISSUE TITLE
Fail2ban Zoraxy

### ISSUE THREAD

**Issue by Julien684** [Tontonjo/docker#1]
Bonjour Tonton Jo,
Pouvez-vous rajouter une section fail2ban pour Zoraxy ?
Cordialement.

**Comment by Tontonjo** [comment]
> Bonjour Tonton Jo, Pouvez-vous rajouter une section fail2ban pour Zoraxy ? Cordialement.

Hello!
C'est pas au programme pour le moment pour la simple raison que.... il n'y a pas de logs à lire.
(autant que je sache)
